const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),http=require('http');
(async()=>{
const base=process.argv[2],out=path.resolve('evidence/web',process.argv[3]||'basic_moves');fs.mkdirSync(out,{recursive:true});let server;
if(base.includes('127.0.0.1')){server=http.createServer((req,res)=>{const file=path.join(process.cwd(),'tmp/web',req.url.split('?')[0].replace(/^\//,'')||'index.html');if(!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',{'.html':'text/html','.js':'application/javascript','.wasm':'application/wasm'}[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(Number(new URL(base).port),'127.0.0.1',r));}
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-swiftshader']});let logs=[],errors=[];
try{const page=await browser.newPage({viewport:{width:1280,height:720}});page.on('console',m=>{logs.push(m.text());fs.appendFileSync(path.join(out,'live.log'),m.text()+'\n');});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});let build='';
await page.route(/index\.html/,async route=>{const response=await route.fetch();let html=await response.text();build=(html.match(/"executable":"([^"]+)"/)||[])[1]||'';const marker='const engine = new Engine(GODOT_CONFIG);';if(!html.includes(marker))throw Error('bootstrap marker missing');html=html.replace(marker,marker+"const originalStart=engine.startGame.bind(engine);engine.startGame=async (...args)=>{await engine.init(GODOT_CONFIG.executable);engine.copyToFS('/userfs/godot/app_userdata/HashireIkazuchi/basic_moves_qa.txt',new TextEncoder().encode('basic_moves_v1').buffer);return originalStart(...args);};");await route.fulfill({response,body:html});});
await page.goto(base,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.basicMovesQAResult,null,{timeout:900000});const result=await page.evaluate(()=>window.basicMovesQAResult);await page.screenshot({path:path.join(out,'completed.png')});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({base,build,result,errors},null,2));if(result.code!==0||result.cases!==240||result.failures.length||errors.length)throw Error(JSON.stringify({result,errors}));console.log('BASIC_MOVES_WEB_CHECK '+JSON.stringify({build,...result}));
}finally{fs.writeFileSync(path.join(out,'console.log'),logs.join('\n'));await browser.close();if(server)await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
